# Generated by Django 4.0.3 on 2022-05-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('puntos', models.IntegerField()),
                ('partidos_ganados', models.IntegerField()),
                ('partidos_perdidos', models.IntegerField()),
                ('partidos_empatados', models.IntegerField()),
                ('goles_favor', models.IntegerField()),
                ('goles_contra', models.IntegerField()),
                ('diferencia_goles', models.IntegerField()),
                ('posicion', models.IntegerField()),
            ],
        ),
    ]
