# Generated by Django 4.0.3 on 2022-05-13 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='equipo',
            order_with_respect_to='posicion',
        ),
    ]
