# Generated by Django 4.0.3 on 2022-05-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_equipos', '0002_alter_equipo_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['-posicion']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='equipo',
            order_with_respect_to=None,
        ),
    ]
