# Generated by Django 4.0.3 on 2022-05-13 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_equipos', '0003_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['posicion']},
        ),
    ]
