# Generated by Django 4.0.4 on 2022-05-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_equipos', '0004_alter_equipo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='localidad',
            field=models.CharField(default='ssss', max_length=50),
            preserve_default=False,
        ),
    ]
