# Generated by Django 4.0.4 on 2022-05-13 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_equipos', '0005_equipo_localidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrantes_Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('posicion', models.CharField(max_length=50)),
                ('goles', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabla_equipos.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugador',
            field=models.ForeignKey(default='www', on_delete=django.db.models.deletion.CASCADE, related_name='jugador', to='tabla_equipos.integrantes_equipo'),
            preserve_default=False,
        ),
    ]
