# Generated by Django 4.0.4 on 2022-05-13 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_equipos', '0006_integrantes_equipo_equipo_jugador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='jugador',
        ),
        migrations.DeleteModel(
            name='Integrantes_Equipo',
        ),
    ]
